apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ablock-tenant/rhtap-partner-catalog/partner-catalog@sha256:1d671ed76937acd7c8b4503f52bda8a6116c46e9d6b48ee217095cee66095021
        name: my-java-springboot
        resources: {}
status: {}
