apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ablock-tenant/rhtap-partner-catalog/partner-catalog@sha256:fb1ad1ae97998008e4394a320aed3a1511fe73ea4c8f0ce9d590df990b471c05
        name: my-java-springboot
        resources: {}
status: {}
